cdl_mdm={
    'banner_latest_process':'流程中的banner',
    'banner_market_mapping':'已审批通过的banner 和rd的mapping',
    'banner_rd_mapping':'已审批通过的banner 和rd的mapping',
	'channel_type_banner_type_mapping':'banner type 和channel type的关系',
    'dms_store_daily':'上游daily 推送的dms store , 有字段变化的store',
    'dms_store_operation_log':'dms_store操作日志',
    'effective_banner':'banner 的黄金记录',
    'effective_banner_from':'起流程banner的来源',
    'effective_banner_group':'起流程的banner group',
    'effective_dms_store':'store的黄金记录， 不更新banner相关的字段',
    'effective_store_banner_from':'起流程的store_banner',
    'effective_store_central_mapping':'重要store的匹配关系',
	'dms_store_operation_log':'给开发看的store变化记录',
	'flag_cdl_data_transfer':'信号表,重要字段：data_type(数据来源)',
	'job_process_store_banner_mapping':'启动store banner mapping流程的job',
	'job_record_store_change':'作业:做字段对比，并生成store_seq',
	'mdm_banner_operation_summary_log':'给用户看的banner变化记录',
	'mdm_store_channel_type':'store_channel_type',
	'mdm_store_operation_summary_log;':'给用户看的store变化记录',
	'mdm_dms_store_list_all':'GP最全量的store',
	'mdm_v5_banner_org':'',
	'MDM_V5_RESPONSIBILITY_NEW;':'',
	'mdm_v5_sales_org_rollup':'',
	'mdm_v5_user_responsibility_serving':'',
	'mismatch_store_banner_deal_process':'审批拒绝记录表，目的是为了做审计',
	'new_store_banner_latest_process':'store banner mapping的流程表',
	'owner_process_instance':'ticket 的清单表',
	'owner_process_instance_approve':'ticket 的用户待办表，处理记录',
	'owner_process_instance_user_info':'ticket 的用户待办表，核心字段',
	'pi_all_next_handler':'历史处理人',
	'pi_rt_next_handler':'当前处理人',
	'pi_task':'流程节点信息表',
    'store_central_process':'重要store处理',
    'store_data_quality_process':'store data quality处理'
    }
	
mdm_acs={
	'api':'',
	'cdh_role_mapping_config':'',
	'data_abstract_tag':'',
	'data_instance_tag':'',
	'function_api':'',
	'user':'',	
	'user_data_abstract_tag':'',
	'user_data_instance_tag':'',
	'user_enable_config':'',
	'user_role':'',
	'user_role_permission_sync_log':'',		
	'role':'',
	'role_function':''	
}
